### ISSUE TITLE
calculator modal

### ISSUE THREAD

**Issue by rudanzona** [rudanzona/react-calculator-modal#1]
# UI design
![ui](https://user-images.githubusercontent.com/4468323/86312174-b64d1080-bc54-11ea-9066-68c0728ccbbd.png)

# Tasks
- Initialization
  - [x] initialize react app by [create-react-app](https://create-react-app.dev/docs/getting-started/)
  - [x] Set up docker-based development env
  - [x] initialize [storybook](https://storybook.js.org/) for demonstrating components
- Components
  - [x] calculator buttons
    - [x] number
    - [x] operator
    - [x] callback
    - [x] selected btn
  - [x] calculator screen
    - [x] result
  - [x] calculator with [React hooks](https://reactjs.org/docs/hooks-intro.html)
     - [x] styles (mobile first)
     - [x] number, operator and result records
        - [x] number
        - [x] dot
        - [x] operators
          - [x] add
          - [x] subtract
          - [x] multiply
          - [x] divide
          - [x] equal
          - [x] percentage
          - [x] clear (AC)
          - [x] sign (+/-)
  - [x] modal with [react-modal](https://www.npmjs.com/package/react-modal)
    - [x] modify styles for mobile devices
       - 彈出後請取固定在畫面最下方
       - 寬度為畫面100%，高度最大為畫面50%，計算機modal可scroll
    - [x] modify styles for desktop
      - 計算機寬度固定為480px
      - 當畫面小於768px時將計算機寬度改為360px
  - [x] drag and drop with [react-draggable](https://github.com/STRML/react-draggable)
    - [x] disable drag and drop on mobile devices
    - [x] enable drag and drop on desktop
    - [x] calculator cannot be placed out side of body
- Integrate calculator with react app
  - [x] 點擊按鈕時彈出計算機
  - [x] 點擊計算機以外介面可關閉計算機
  - [x] store records by [Redux](https://redux.js.org/api/api-reference)
     - [React Redux](https://react-redux.js.org/introduction/quick-start)
     - [redux-toolkit](https://redux-toolkit.js.org/api/configureStore)
- [x] deploy to [github pages](https://pages.github.com/)
- edge cases
  - [ ] large numbers
  - [ ] long fraction digits of numbers
  - [ ] divided by zero
- enhancement
  - [ ] show formula
  - [ ] list use cases and add more unit tests
  - [ ] add integration tests
